ARG CONTAINER_BASE="centos:stream9"

FROM $CONTAINER_BASE

COPY jira-report.py /usr/bin/jira-report.py
COPY jira-report-runner.py /usr/bin/runner.py
COPY requirements.txt /requirements.txt

RUN dnf -y install procps-ng vim-enhanced

RUN dnf -y install cronie \
 && dnf -y update \
 && dnf clean all \
 && rm -rf /var/cache/dnf \
 && python3 -m ensurepip \
 && python3 -m pip install --upgrade pip \
 && pip3 install -r requirements.txt \
 && /usr/sbin/crond

ENTRYPOINT ["/bin/bash"]